JAVA := /usr/bin/java
antlr := lib/antlr-4.9-complete.jar

build: grammar
	@echo "Building binary..."
	go build -o dist/nup

grammar:
	@echo "Compiling grammar..."
	$(JAVA) -jar $(antlr) -Dlanguage=Go -o . parser/NupLexer.g4
	$(JAVA) -jar $(antlr) -Dlanguage=Go -o . parser/NupParser.g4